# Generated by Django 5.2.7 on 2025-11-02 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('quiz', '0003_remove_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='quiz.question'),
        ),
    ]
