# Generated by Django 5.2.7 on 2025-10-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_correct_answer_alter_quiz_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
    ]
